spring.application.name=availability-service

spring.datasource.url=jdbc:postgresql://localhost:5432/availability_service
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

#delays running data.sql until after Hibernate has created/updated the schema.
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator

server.port=8082
