spring.application.name=loan-service
spring.datasource.url=jdbc:postgresql://localhost:5432/loan_service
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=event:com.booknest.loanservice.event.LoanPlacedEvent

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator

resilience4j.circuitbreaker.instances.availability.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.availability.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.availability.slidingWindowSize=5
resilience4j.circuitbreaker.instances.availability.failureRateThreshold=50
resilience4j.circuitbreaker.instances.availability.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.availability.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.availability.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.timelimiter.instances.availability.timeout-duration=3s
resilience4j.retry.instances.availability.max-attempts=3
resilience4j.retry.instances.availability.wait-duration=5s

server.port=8081
